services:
  db:
    image: postgres:latest
    container_name: play_ground_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    container_name: play_ground_redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:4
    container_name: play_ground_localstack
    ports:
      - "4568:4566"
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
    environment:
      - ACTIVATE_PRO=0

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - '16686:16686'
      - '4318:4318'
    volumes:
      - ./jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    environment:
      - JAEGER_UI_CONFIG=/etc/jaeger/jaeger-ui.json
