version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: play_ground_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - "5434:5432"

  localstack:
    image: localstack/localstack:0.14.1
    container_name: play_ground_localstack
    ports:
      - "4568:4566"
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"
    environment:
      - SERVICES=sns,s3
